#ifndef STATUS_H_
#define STATUS_H_

typedef enum status {
    STATUS_OK = 0,
    STATUS_ERROR = 1,

    CBUF_STATUS_BUFFER_OVERFLOW = 100,
    CBUF_STATUS_CBUF_FULL,
    CBUF_STATUS_CBUF_EMPTY,

    SPACEPACKET_STATUS_INVALID_VERSION = 200,
    SPACEPACKET_STATUS_INVALID_TYPE,
    SPACEPACKET_STATUS_INVALID_SEC_HDR,
    SPACEPACKET_STATUS_INVALID_APID,
    SPACEPACKET_STATUS_INVALID_APID_HANDLER,

    ACTION_STATUS_INVALID_HANDLER_REGISTRATION = 300,
    ACTION_STATUS_INVALID_PAYLOAD_SIZE,
    ACTION_STATUS_INVALID_ACTION_ID,
} status_t;

#endif /* STATUS_H_ */
